server:
  port: 8003

spring:
  application:
    name: eureka-server-cluster

eureka:
  instance:
    hostname: peer3
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/